# espanso match file

matches:
  - trigger: ";gid"
    replace: "HirokiMorishita"
  - trigger: ":shebang"
    replace: "#!/usr/bin/env bash"

  - trigger: ";mdlink"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  - trigger: ";details"
    replace: "<details>\n<summary>$|$<summary>\n\n```\n```\n</details>"

  - trigger: ";nowl"
    replace: "{{now}}"
    vars:
      - name: now
        type: shell
        params:
          cmd: "date '+%Y-%m-%dT%H:%M:%S%:z'"
  - trigger: ";nowu"
    replace: "{{now}}"
    vars:
      - name: now
        type: shell
        params:
          cmd: "date -u '+%Y-%m-%dT%H:%M:%SZ'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/